-- Recrée la table avec la colonne statut
drop table if exists exam_aspirant;

create table exam_aspirant (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  name text not null,
  score int,
  correct int,
  total int,
  time_left int,
  finished boolean default false,
  eliminated boolean default false,
  answers jsonb,
  statut text default 'attente'
);

alter table exam_aspirant enable row level security;

create policy "insert_exam" on exam_aspirant
  for insert to anon with check (true);

create policy "read_exam" on exam_aspirant
  for select to anon using (true);

create policy "update_statut" on exam_aspirant
  for update to anon
  using (true)
  with check (true);
